#!/usr/bin/env node
/**
 * Antigram Setup Wizard
 * Interactively prompts for configuration and saves to .env file.
 */

const readline = require('readline');
const fs = require('fs');
const path = require('path');

const ENV_FILE = path.join(__dirname, '.env');
const ENV_EXAMPLE_FILE = path.join(__dirname, '.env.example');

// ANSI color codes for pretty output
const c = {
    reset: '\x1b[0m',
    bold: '\x1b[1m',
    dim: '\x1b[2m',
    green: '\x1b[32m',
    cyan: '\x1b[36m',
    yellow: '\x1b[33m',
    red: '\x1b[31m',
    blue: '\x1b[34m',
    magenta: '\x1b[35m',
};

function print(msg) { process.stdout.write(msg + '\n'); }
function bold(msg) { return `${c.bold}${msg}${c.reset}`; }
function dim(msg) { return `${c.dim}${msg}${c.reset}`; }
function green(msg) { return `${c.green}${msg}${c.reset}`; }
function cyan(msg) { return `${c.cyan}${msg}${c.reset}`; }
function yellow(msg) { return `${c.yellow}${msg}${c.reset}`; }
function red(msg) { return `${c.red}${msg}${c.reset}`; }
function blue(msg) { return `${c.blue}${msg}${c.reset}`; }

function banner() {
    print('');
    print(bold(cyan(' ╔══════════════════════════════════════════╗')));
    print(bold(cyan(' ║                                          ║')));
    print(bold(cyan(' ║       🤖  Antigram Setup Wizard          ║')));
    print(bold(cyan(' ║       Telegram → IDE Bridge Bot          ║')));
    print(bold(cyan(' ║                                          ║')));
    print(bold(cyan(' ╚══════════════════════════════════════════╝')));
    print('');
}

function loadExistingEnv() {
    const config = {};
    if (fs.existsSync(ENV_FILE)) {
        const content = fs.readFileSync(ENV_FILE, 'utf8');
        for (const line of content.split('\n')) {
            const trimmed = line.trim();
            if (!trimmed || trimmed.startsWith('#')) continue;
            const eqIdx = trimmed.indexOf('=');
            if (eqIdx === -1) continue;
            const key = trimmed.substring(0, eqIdx).trim();
            const val = trimmed.substring(eqIdx + 1).trim();
            config[key] = val;
        }
    }
    return config;
}

function saveEnv(config) {
    const lines = [
        '# Antigram Bot Configuration',
        '# Generated by setup wizard on ' + new Date().toLocaleString(),
        '',
        '# Telegram Bot Token (from @BotFather)',
        `TELEGRAM_BOT_TOKEN=${config.TELEGRAM_BOT_TOKEN || ''}`,
        '',
        '# Comma-separated Telegram User IDs allowed to use this bot',
        `TELEGRAM_USER_ID=${config.TELEGRAM_USER_ID || ''}`,
        '',
        '# Chrome DevTools Protocol port (default: 9222)',
        `CDP_PORT=${config.CDP_PORT || '9222'}`,
        '',
        '# Path to IDE executable (optional)',
        `ANTIGRAVITY_PATH=${config.ANTIGRAVITY_PATH || '/usr/bin/antigravity'}`,
        '',
    ];

    if (config.WIT_AI_TOKEN) {
        lines.push('# Wit.ai Token for Voice Notes (free, optional)');
        lines.push(`WIT_AI_TOKEN=${config.WIT_AI_TOKEN}`);
        lines.push('');
    }

    fs.writeFileSync(ENV_FILE, lines.join('\n'), 'utf8');
}

function ask(rl, question, defaultVal) {
    return new Promise((resolve) => {
        const hint = defaultVal ? dim(` [${defaultVal}]`) : '';
        rl.question(`  ${cyan('?')} ${bold(question)}${hint}: `, (answer) => {
            resolve(answer.trim() || defaultVal || '');
        });
    });
}

async function runSetup(forceReconfigure = false) {
    banner();

    const existing = loadExistingEnv();

    const hasRequired = existing.TELEGRAM_BOT_TOKEN && existing.TELEGRAM_USER_ID;

    if (hasRequired && !forceReconfigure) {
        print(green(' ✅ Configuration already exists in .env file.'));
        print(dim(`    Bot Token  : ${existing.TELEGRAM_BOT_TOKEN.substring(0, 12)}...`));
        print(dim(`    User IDs   : ${existing.TELEGRAM_USER_ID}`));
        print('');
        print(' To reconfigure, run: ' + bold(cyan('node setup.js --reconfigure')));
        print('');
        return;
    }

    if (!hasRequired) {
        print(yellow(' ⚠️  No configuration found. Let\'s set up your bot!'));
    } else {
        print(yellow(' 🔄  Reconfiguration mode — press Enter to keep existing values.'));
    }
    print('');

    const rl = readline.createInterface({
        input: process.stdin,
        output: process.stdout,
    });

    print(bold(' Step 1: Telegram Bot Token'));
    print(dim('   Get this from @BotFather on Telegram → /newbot'));
    const botToken = await ask(rl, 'Bot Token', existing.TELEGRAM_BOT_TOKEN);

    if (!botToken || !botToken.includes(':')) {
        print(red('\n ❌ Invalid token format. Token should look like: 123456:ABC-DEF...\n'));
        rl.close();
        process.exit(1);
    }

    print('');
    print(bold(' Step 2: Authorized Telegram User ID(s)'));
    print(dim('   Find your User ID by messaging @userinfobot on Telegram'));
    print(dim('   You can add multiple IDs separated by commas: 12345,67890'));
    const userId = await ask(rl, 'User ID(s)', existing.TELEGRAM_USER_ID);

    if (!userId || !/^[\d,\s]+$/.test(userId)) {
        print(red('\n ❌ Invalid User ID. Must be numeric (e.g. 123456789)\n'));
        rl.close();
        process.exit(1);
    }

    print('');
    print(bold(' Step 3: Advanced Settings'));
    print(dim('   Press Enter to use defaults for the following:'));
    const cdpPort = await ask(rl, 'CDP Debugging Port', existing.CDP_PORT || '9222');
    const antigravityPath = await ask(rl, 'IDE Executable Path', existing.ANTIGRAVITY_PATH || '/usr/bin/antigravity');

    print('');
    print(bold(' Step 4: Optional — Wit.ai Voice Token'));
    print(dim('   Get a free token at https://wit.ai (for Telegram voice notes)'));
    print(dim('   Leave blank to skip voice note support'));
    const witToken = await ask(rl, 'Wit.ai Token', existing.WIT_AI_TOKEN || '');

    rl.close();

    const config = {
        TELEGRAM_BOT_TOKEN: botToken,
        TELEGRAM_USER_ID: userId.replace(/\s/g, ''),
        CDP_PORT: cdpPort,
        ANTIGRAVITY_PATH: antigravityPath,
        ...(witToken ? { WIT_AI_TOKEN: witToken } : {}),
    };

    saveEnv(config);

    print('');
    print(bold(green(' ✨ Configuration saved to .env successfully!')));
    print('');
    print(bold(' Summary:'));
    print(`   ${green('✓')} Bot Token  : ${config.TELEGRAM_BOT_TOKEN.substring(0, 12)}...`);
    print(`   ${green('✓')} User IDs   : ${config.TELEGRAM_USER_ID}`);
    print(`   ${green('✓')} CDP Port   : ${config.CDP_PORT}`);
    print(`   ${green('✓')} IDE Path   : ${config.ANTIGRAVITY_PATH}`);
    if (witToken) print(`   ${green('✓')} Wit Token  : ${witToken.substring(0, 10)}...`);
    print('');
    print(' Now start the bot with: ' + bold(cyan('npm start')));
    print('');
}

// CLI argument handling
const args = process.argv.slice(2);
const forceReconfigure = args.includes('--reconfigure') || args.includes('-r');

runSetup(forceReconfigure).catch((err) => {
    console.error(red('\n ❌ Setup failed: ' + err.message));
    process.exit(1);
});
